apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  name: plo-db-deployment
  labels:
    app: plo
    component: db
spec:
  replicas: {{ .Values.db.replicaCount }}
  serviceName: {{ .Values.db.service.name | default "plo-db-service" }}
  selector:
    matchLabels:
      app: plo
      component: db
  template:
    metadata:
      labels:
        app: plo
        component: db
    spec:
      containers:
        - name: {{ .Values.db.name }}
          image: {{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}
          imagePullPolicy:  {{ .Values.db.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.db.image.containerPort }}
              name: postgres
              protocol: TCP
          envFrom:
            - configMapRef:
                name: plo-backend-config
            - secretRef:
                name: {{ .Values.db.existingSecret }}
          resources:
            requests:
              cpu: {{ .Values.db.resources.requests.cpu }}
              memory: {{ .Values.db.resources.requests.memory }}
            limits:
              cpu: {{ .Values.db.resources.limits.cpu }}
              memory: {{ .Values.db.resources.limits.memory }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data # Must match the metadata.name in volumeClaimTemplates below
              subPath: postgres
          readinessProbe:
            exec:
              command: [ "pg_isready", "-U", "postgres" ]
            initialDelaySeconds: 5
            timeoutSeconds: 5
  # Kubernetes automatically creates the PVC using this template
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes:
          - {{ .Values.db.persistence.accessMode | default "ReadWriteOnce" }}
        storageClassName: {{ .Values.db.persistence.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.db.persistence.size }}