apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.service.name | default "plo-db-service" }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app: plo
    component: db
spec:
  type: {{ .Values.db.service.type | default "ClusterIP" }}
  {{- if .Values.db.service.clusterIP }}
  clusterIP: {{ .Values.db.service.clusterIP }}
  {{- end }}
  selector:
    app: plo
    component: db
  ports:
    - name: postgres
      port: {{ .Values.db.service.port | default 5432 }}
      targetPort: {{ .Values.db.service.targetPort | default 5432 }}
      protocol: TCP