apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  name: plo-backend-deployment
  labels:
    app: plo
    component: plo-backend
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: plo
      component: plo-backend
  template:
    metadata:
      labels:
        app: plo
        component: plo-backend
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.image.containerPort }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.app.env.SPRING_PROFILES_ACTIVE }}
          envFrom:
            - configMapRef:
                name: plo-backend-config
            - secretRef:
                name: {{ .Values.app.existingSecret }}
          resources:
            requests:
              cpu: {{ .Values.app.resources.requests.cpu }}
              memory: {{ .Values.app.resources.requests.memory }}
            limits:
              cpu: {{ .Values.app.resources.limits.cpu }}
              memory: {{ .Values.app.resources.limits.memory }}
          readinessProbe:
            httpGet: {path: {{ .Values.app.probes.readiness.path }}, port: {{ .Values.app.image.containerPort }}}
            initialDelaySeconds: {{ .Values.app.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet: {path: {{ .Values.app.probes.liveness.path }}, port: {{ .Values.app.image.containerPort }}}
            initialDelaySeconds: {{ .Values.app.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.probes.liveness.periodSeconds }}