apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plo-ingress
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app: plo
    component: ingress
  annotations:
      {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host | default "personallearningos.rksdev.tech" }}
      secretName: {{ .Values.ingress.tls.secretName | default "plo-tls-cert" }}
  rules:
    - host: {{ .Values.ingress.host | default "personallearningos.rksdev.tech" }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: plo-backend-service
                port:
                  number: {{ .Values.app.service.port | default 2266 }}
